# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7320aa9fec854f653e83fb17d04f2bc233d4660145e7bf8320afb8c70e4e3a8a89b85455965e8edf486ed95ab86b7ed7295d8cea0447b57cade556821fe822d5

test:
  secret_key_base: c9a9a8b0b255f3e3cc118cac1efbb25b9c5642a0784f508b1a11dd8ce256e56c768fa5bafde96a34a4e3de27f98ceb9d21a09cbb15d00071ef6be076fe0e8527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
